language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - sudo apt-get -qq update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip six numpy scipy
  - source activate test-environment
  - travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py install
script:
  - coverage run --source pyret -m py.test
after_success:
  - bash <(curl -s https://codecov.io/bash)
